create table
  public.places (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    types text[] null,
    short_name text not null,
    image text null,
    bounds jsonb null,
    latlng jsonb null,
    viewport jsonb null,
    name json null,
    geo_point geography null,
    constraint places_pkey primary key (id, short_name)
  ) tablespace pg_default;

create unique index places_short_name_idx on public.places using btree (short_name) tablespace pg_default;
ALTER TABLE "public"."places" ENABLE ROW LEVEL SECURITY;

CREATE POLICY  "places_view_policy" ON "public"."places" FOR SELECT TO "authenticated", "anon" USING (true);
GRANT ALL ON TABLE "public"."places" TO "anon";
GRANT ALL ON TABLE "public"."places" TO "authenticated";
GRANT ALL ON TABLE "public"."places" TO "service_role";
