create table
  public.room_availability (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    room_id bigint not null,
    cost smallint null default '10'::smallint,
    is_available boolean null default true,
    date date not null,
    constraint room_availability_pkey primary key (id),
    constraint room_availability_room_id_fkey foreign key (room_id) references variants (id) on update cascade on delete cascade
  ) tablespace pg_default;

create unique index room_availability_unique_idx on public.room_availability using btree (room_id, date) tablespace pg_default;
