'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const queryClient = new QueryClient();

import ar from "src/lib/transulations/ar.json";
import en from "src/lib/transulations/en.json";
import LoadingSpinnerComponent from "react-spinners-components";
import { Tolgee, DevTools, FormatSimple, BackendFetch, TolgeeProvider } from "@tolgee/react";
import { UserProvider } from "@/providers/userProvider";
import Header  from "@/components/layout/header";

const tolgee = Tolgee()
  .use(DevTools())
  .use(FormatSimple())
  .use(
    BackendFetch({
      prefix: "https://cdn.tolg.ee/5a3e507bbe8d15821632432a003addf5",
    })
  )
  .init({
    language: "ar",
    fallbackLanguage: "en",
    onTranslationMissing: (info) => {
      console.debug("missing transulation :>> ", info);
      return info.key;
    },
    availableLanguages: ["ar", "en"],
    // for development
    apiUrl: process.env.VITE_APP_TOLGEE_API_URL,
    apiKey: process.env.VITE_APP_TOLGEE_API_KEY,

    // for production
    staticData: {
      ar,
      en,
    },
  });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <title>Manazl Oman Hostels and Hotels</title>
        <meta title="description" content="Oman Travel Booking hostels and hotels "></meta>
        <link rel="icon" href="/favicon.png" sizes="any" />
      </head>
      <body className={inter.className}>

        <QueryClientProvider client={queryClient}>
          <UserProvider>
            <TolgeeProvider tolgee={tolgee} fallback={< LoadingSpinnerComponent />}>
              <Header />
              <div className="h-24"></div>
              {children}
            </TolgeeProvider>
          </UserProvider>
          <Toaster />
        </QueryClientProvider>
      </body>


    </html>
  );
}
